######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 1 00:09:16 2018
######################################################################

TEMPLATE = app
TARGET = tab
DEPENDPATH += .
INCLUDEPATH += .

QT = core quick

# Input
SOURCES += main.cpp
RESOURCES += qml.qrc
